// <auto-generated/>
// 多 worktree 并行调试用的身份后缀。
//
// 由 DockedTools.csproj 的 _WriteWorktreeIdentity target 在每次构建时覆盖：
//   Debug + 仓库目录名形如 main-ffb0958c  →  ".WTFFB0"
//   其余情况（Release、目录名不含 hash）  →  ""（行为与改动前完全一致）
//
// 它同时决定两件事，二者必须同源，否则会出现「能装不能跑」：
//   1. MSIX 包身份  Identity Name  = 8B8CC4F4.482486777ECD9.Debug + 本后缀
//   2. 运行时单实例标识（Mutex / 事件 / 命名管道）+ 本后缀
//
// 放在全局命名空间，方便各处直接用 global::WorktreeIdentity.Suffix 取到。
internal static class WorktreeIdentity
{
    public const string Suffix = "";
}
